### ISSUE TITLE
LNURL static QR code does not conform LUD-01

### ISSUE THREAD

**Issue by andrei-21** [GaloyMoney/galoy-mobile#3295]
**Describe the bug**
LNURL static QR code does not conform  [LUD-01 fallback scheme](https://github.com/lnurl/luds/blob/luds/01.md#fallback-scheme). The `LIGHTNING` parameter is uppercased, but has to be lowercased.

**To Reproduce**

1. Go to 'Setting'
2. Click on 'Printable static QR code'
3. The url has `LIGHTNING` parameter

**Expected behavior**
The url has `lightning` parameter.

**Smartphone (please complete the following information):**

- Device: Pixel
- OS: Android

**Additional context**
A similar issue has already appeared, but has been fixed: https://github.com/GaloyMoney/blink-mobile/issues/2520.

**Comment by al-munazzim** [comment]
## Implementation Plan for #3295

### Summary
Fix LUD-01 fallback scheme violation where `lightning=` parameter is incorrectly uppercased to `LIGHTNING=` in the printable static QR code.

### Root Cause
The print page in `apps/pay/app/[username]/print/page.tsx` (line 25) uses:
```javascript
const qrCodeURL = (webURL + "?lightning=" + lnurl).toUpperCase()
```

This uppercases the entire URL including the `lightning=` parameter key. Per [LUD-01 fallback scheme](https://github.com/lnurl/luds/blob/luds/01.md#fallback-scheme), the `lightning` parameter key MUST be lowercase, while the LNURL value itself can be uppercase (which is actually preferred for QR code efficiency).

### Proposed Fix

**Repository:** `blinkbitcoin/blink` (monorepo)
**File:** `apps/pay/app/[username]/print/page.tsx`
**Complexity:** Trivial (1 line change)

**Change:**
```diff
- const qrCodeURL = (webURL + "?lightning=" + lnurl).toUpperCase()
+ const qrCodeURL = webURL.toUpperCase() + "?lightning=" + lnurl.toUpperCase()
```

This keeps `lightning=` lowercase while uppercasing the URL host/path and LNURL value, which is the correct format per LUD-01.

### Prior Art
This is the same fix that was applied to the mobile app in PR #2521 for issue #2520. The print page was likely not updated at that time.

### Testing Plan
- [ ] Verify generated QR code URL has lowercase `lightning=` parameter
- [ ] Verify QR code scans correctly in strict LUD-01 compliant wallets
- [ ] Visual inspection of printable QR code page

### Risks & Considerations
- **Very low risk** - This is a one-line change to string formatting
- The LNURL value itself should remain uppercase for QR code scanning efficiency
- Only the parameter key changes, not the value

### Note on Repository
This issue was filed in `blink-mobile` but the bug is in the `blink` monorepo's pay app. The mobile app's in-app QR generation was fixed in #2521, but the server-side print endpoint was not.
